### ISSUE TITLE
Performance improvements

### ISSUE THREAD

**Issue by awdeorio** [eecs485staff/madoop#34]
There are a few opportunities to make Madoop faster.

- [x] Do not copy input.  Instead, read input files directly.  For larger files which need to be split, read an iterator over a segment of the input file.
- [x] Do not copy output.  Move final output instead of copying it.
- [ ] Do not store both map output and partitioned map output.  Instead, pipe map output directly to partition function.
- [ ] Do store both sorted and unsorted group output.  Instead, read partitioned mapper output into memory (one file).  Sort it.  Pipe sorted output to reducer input.
- [x] Measure run time with a large input (e.g., EECS 485 Project 5 Wikipedia input) and optimize input partition size.
- [x] Parallelism with a thread pool
- [x] Don't read intermediate files again to calculate statistics for DEBUG output.  This is a bad one and it even runs when DEBUG output is disabled. #41

**Comment by jaredzh** [comment]
For the first bullet, how would we pass an iterator into `subprocess.run`?

**Comment by awdeorio** [comment]
> Do not copy input. Instead, read input files directly. For larger files which need to be split, read an iterator over a segment of the input file.

You don't need to change the call to `subprocess.run`, it's still going to have a file handle as input.  The only difference is that it should read the original input file path provided by the user.  Don't copy the input.

**Comment by jaredzh** [comment]
But for the large files that need to be split, how will the user program know when to stop reading the original large input file if the input is a file handle? Should the input instead be the actual text that is read from a section of the input file?

**Comment by awdeorio** [comment]
> But for the large files that need to be split, how will the user program know when to stop reading the original large input file if the input is a file handle? Should the input instead be the actual text that is read from a section of the input file?

This is tricky.  I think the right solution is to pass around iterators instead of passing around files.  Then, you can use the same technique used by `itertools.groupby()`, which is to "break up" an interator into smaller nested iterators.  Generators are great for this!
