### ISSUE TITLE
Version 1.0

### ISSUE THREAD

**Issue by awdeorio** [eecs485staff/madoop#40]
Bump to Version 1.0 after integrating with, and testing against EECS 485 Project ~~4~~ 5.

**Comment by jaredzh** [comment]
Did you mean integrating with and testing against Project 5?

**Comment by awdeorio** [comment]
> Did you mean integrating with and testing against Project 5?

Yep!  My mistake.

**Comment by jaredzh** [comment]
Closed per [Madoop Dependency](https://github.com/eecs485staff/p5-search-engine/pull/562)
