### ISSUE TITLE
Report error messages from subprocesses

### ISSUE THREAD

**Issue by noah-weingarden** [eecs485staff/madoop#50]
It would be nice if Madoop would report error messages reported by map or reduce executables that are run as subprocesses. Perhaps there could be a `debug` command-line option which specifies whether or not to do this? Or the current `verbose` option could enable it.

**Comment by 738993** [comment]
strickland59801550@gmail.com

**Comment by awdeorio** [comment]
I like this.  I think that it would be OK for an error to propagate straight to the output without needing to re-run with an option.
