### ISSUE TITLE
Madoop does not work with directories in file path containing spaces

### ISSUE THREAD

**Issue by jakeump** [eecs485staff/madoop#72]
My file directory was /Code/EECS 485/project, and when trying to run Madoop, I got a 127 error -- file not found. Upon downgrading Madoop to 1.0.1, the error was more explicit, listing the path. I had to change my directory to EECS-485, as well as reinstall my virtual environment for each project in the directory. Only then could I get the Madoop example to work.

I know it's bad style to have spaces, but I'm sure Madoop doesn't intend to not support these erroneously-named directories.

**Comment by awdeorio** [comment]
Thanks for the bug report.  We'll take a look.
