### ISSUE TITLE
Add custom partitioning to the Madoop documentation

### ISSUE THREAD

**Issue by mbaveja** [eecs485staff/madoop#77]
Madoop documentation should include information about the new custom partitioning per #71.
This is needed for the Project 5 spec in [this PR](https://github.com/eecs485staff/p5-search-engine/pull/710).

**Comment by noah-weingarden** [comment]
I'll take care of this today!

**Comment by mbaveja** [comment]
Sounds good! We will likely replace the link in new PR so we can merge [this one](https://github.com/eecs485staff/p5-search-engine/pull/710) ASAP.
